### PR TITLE
Fix #2 "URL does not change when swiching from one page to another"

### LINKED ISSUE #1: Possibly need to remove location.href regex check?
For the below code in your main.js file, should this be left out of your code? It seems that if you navigate to the Forks page from the Insights tab, the page URL doesn't update to match the regex while navigating to it.

[`if (githubUrlRegex.test(location.href)) {`](https://github.com/giacomoferretti/forks-diff/blob/106d8db8379f79ca36ffaa294be2f97d76140c2c/js/main.js#L136)

### LINKED ISSUE #2: URL does not change when swiching from one page to another
Hi. Thank you for this useful extension.  
The GitHub URL does not change when I move from one page to another when this extension enabled.  

### screenshot

https://user-images.githubusercontent.com/60678028/187073681-9bd0ddfc-4681-40c8-8cbd-47163897f7dd.mov

### Steps to reproduce

1. Enable this extension.
1. visit any repository.
1. click something. ex) "Issue"

### Expected behaviour
- The Url should end with "/issue".
- The Issue tab should be underlined.

### Environment
macOS 12.5.1  
Chrome 104.0.5112.101（Official Build） （x86_64）  
Forks Diff Counter for GitHub v1.2.1

### PR DESCRIPTION
**Pull request by taikis**
Fix #2 and we can close #1   

I have confirmed that it works with Chrome. But I couldn't confirm with Firefox because it doesn't support manifest v3.  
How did you deal with this problem?

### CODE REVIEW

File: js/background.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+const githubUrlRegex = /https?:\/\/github\.com\/.*\/network\/members/;
+if (typeof browser === "undefined") {
+    var browser = chrome;
+}
+
+browser.tabs.onUpdated.addListener(function (tabId, info, tab) {
+	if (
+		info.status === "complete" &&
+		tab.title.indexOf("Fork") !== -1 &&
```
Comment (giacomoferretti) [inline js/background.js]:
```js
tab.title.indexOf("Fork") !== -1 &&
```

Is this check really necessary? I don't like it because it depends on the language of the browser.
GitHub is only available in English, but I've seen people use the translator and the latter also changes the title, if I'm not mistaken.

**Review by giacomoferretti — CHANGES_REQUESTED** [review]

**Comment by giacomoferretti** [comment]
> But I couldn't confirm with Firefox because it doesn't support manifest v3. How did you deal with this problem?

I usually convert it back to V2 just for Firefox.

File: js/background.js (hunk 1 above)
Comment (taikis) [reply js/background.js]: Thanks for the review. I have the same opinion as you.  But if I delete this code, it will not work properly.  

GitHub has called `browser.tabs.onUpdated.addListener` several times, two of those times `info.status === "complete"`. I add `tab.title.indexOf("Fork") !== -1` for apply the process only once at the end.   

If you know of another workaround, it would be better to go that way.

Comment (taikis) [reply js/background.js]: Ironically, I found that this code does not work in this repository.  Because this repository name is "fork"-diff.  
I convert this pull request to draft. This process may need to be radically changed.  I'm sorry.

Comment (giacomoferretti) [reply js/background.js]: Don't worry, thank you very much for the PR!

Comment (taikis) [reply js/background.js]: Thank you. If you find a solution, please ignore this pull request and fix it.

**Comment by giacomoferretti** [comment]
Ok, found a proper fix!

**Review by giacomoferretti — APPROVED** [review]
LGTM!
